Homework02

In [25]:
import pandas as pd
import numpy as np

#pd.set_option('display.max_columns', 100)
#pd.set_option('display.max_rows', 500)
df=pd.read_csv('loans_income.csv')
df

            x
0       67000
1       52000
2      100000
3       78762
4       37041
...       ...
49995   40000
49996   54000
49997   50000
49998   82000
49999   70000

[50000 rows x 1 columns]

In [35]:
np.random.choice(df['x'],replace=False, size=1000)

array([125000,  50000,  78000, 110000,  75000,  66283, 110000,  57800,
        49380,  30000, 104000,  40000,  50000,  50000,  78000,  48082,
        70000, 175000, 100000,  94800, 180000, 110000, 133000,  85000,
        72000,  85000,  43000, 120108,  45000,  46000,  60000,  48000,
        68000,  55000,  22800,  30000,  60000,  75000,  25000, 150000,
        38000,  45000,  58666,  34000,  90000,  65000,  37000, 102000,
        64000,  65000,  56000,  57000,  54879,  27000,  48000,  80000,
        80000,  45000,  36000, 120000,  54000,  90000,  80000,  42000,
        19000,  50000,  52000,  85000, 110000,  75000,  70000,  49800,
        48000, 120000,  75000,  90000,  40000,  37000, 110000,  68000,
        48000,  50000, 144000,  65000,  39960,  95000,  35000,  40000,
       105000, 190000,  56000,  63000,  32500,  68000,  46000,  40000,
        75000,  60000,  93000, 118000, 140000,  86000,  67511,  42000,
        80000,  84500,  48434,  65000,  50000,  70000,  43200,  52000,
        84000, 128000, 110000,  35000,  64140,  45000,  97500,  45000,
        73000,  50000,   7200,  52000,  32000,  51012, 110000,  60000,
        40000,  82200,  55000,  65000,  47627,  30000,  36000,  77000,
        87110,  92000, 105000,  66000,  45000,  40000,  60000,  60000,
       140000,  65000,  95000,  82000,  58000,  65000,  60000,  12000,
        19000,  33500,  60000,  74000,  78000,  70000, 136000,  23842,
        80000,  48000, 150750,  89450,  28944,  75000,  28500, 195000,
        51996, 110000,  61000,  59000,  78000,  29000,  33000,  62000,
        21000,  32000, 117500,  49200, 145000,  68000,  70000,  37000,
       116000,  35000,  45000,  75000,  50000,  51000,  55000,  98700,
        52000, 187650,  59000,  77248,  41000,  80000,  75000,  97019,
       150000, 115000,  90000,  81400,  65000,  80000,  42537,  45600,
        55000, 150000,  42000,  51376,  50000,  65000,  52000,  60000,
        40000, 107000,  47000,  95800,  34000,  53000,  75000, 158500,
        37000,  40000,  60000,  80000,  34800, 150000, 190000,  36300,
        82500, 105000,  50000,  74000,  58000,  74000,  50000,  65000,
        42000,  30000, 100000,  45968, 109000,  97000,  63000, 100000,
       100000,  52000, 125000,  41850, 125000,  85000,  45000,  60171,
       180000,  61763,  50000,  54000,  30000, 135000,  42806,  35000,
       110000,  58000,  24000,  85000,  57000,  75000,  95000,  38000,
        61000,  68000,  83000,  61000, 135000,  38000,  27000,  81000,
        43000,  50000,  65000,  45000,  35000, 120000,  88000,  65000,
        84000,  80000,  73000,  24000,  82000,  24000, 101000,  48000,
        41356,  24000,  92000,  40000,  56500,  40000,  45000,  47544,
        38000, 127810,  16048,  45000, 175000,  42000,  48000, 105000,
        56000,  35000,  51000,  76000,  60000,  66000,  45000,  69000,
        83700, 143150,  68000,  24000,  68000,  86524, 125000,  23000,
       130000,  35000,  45000,  56600,  40000,  90231, 100366,  97000,
       140000,  48000, 140000,  48960,  55000, 130000,  85000,  87000,
       160000,  60000,  70000,  85000,  31000,  41000,  47000,  38500,
        40000,  35000,  51000,  80000,  42000,  75000,  67512,  82000,
        90000, 156000,  50000,  50450,  60000,  95000,  57864,  32000,
       125000,  70000,  80000,  41400,  75000,  87000, 180000, 164542,
        30000,  31200,  76000,  65000, 145000,  56000,  95000,  32000,
        80000,  78000,  70000,  82000,  29100,  75000,  40000,  35000,
        42000, 140000,  60000,  30000,  53000,  80000, 110000,  42000,
        47000,  24000,  41000,  95000, 140000,  30000,  41300,  46000,
        30000,  65000, 136000,  25838,  25000,  38000,  50000,  60000,
        90000,  38160,  83000,  93000,  98200,  81000,  76000,  69000,
       100000,  80000,  45090, 105000,  75000,  91000,  70000,  85000,
        50000,  51200,  66000,  65000,  80000,  50000,  32000, 100000,
       147000,  57000,  73500,  70900, 119000,  74767,  97000,  68940,
        41000,  61000,  50000,  73000,  45000,  60000,  24672,  56000,
        75000,  77000,  56800,  37000,  60000,  70000,  30000,  92000,
        75000,  32000,  35100,  93000,  85000,  56000,  61000,  60000,
        95892, 150000,  84600, 129700,  70000,  55000,  32000,  48000,
        80000,  44000, 125000,  70000, 115000,  55498, 110000,  33000,
        30000,  35000,  68500,  45000,  24000,  34000, 187500, 150000,
       135600,  48000,  38000,  60000,  63924,  33000,  68000,  75000,
        60000, 115000,  70000,  60000,  40000,  38300,  72000,  70000,
        61000, 127000,  82000, 165000,  60000, 130000,  50000,  25000,
        68800,  31000,  52000,  91000,  63576,  93600,  40000,  85000,
        39600,  90000, 136000,  30000,  98000,  44782,  29000,  35000,
        24000,  87000,  86000,  48150,  92700,  57000, 106000,  61027,
       110000,  40000,  88000, 125000,  45000,  48000, 110000,  58000,
        52000,  90000,  57000, 123700, 120000,  78000,  96000,  97500,
        83000,  60000, 125000, 115000,  65000,  99000,  72000,  96000,
        82000,  75000, 135000,  74000,  55000, 184000,  88000,  56000,
        65000,  55000,  30000,  87000,  87500,  38000,  75000,  55000,
        38000,  30000, 110000,  90000,  90000, 120000,  90000,  70000,
         8400, 100000,  52000,  84000,  95000,  28400,  45000,  80000,
        85000,  40000,  68000,  45000,  40000,  45000,  60000,  28000,
        32000,  45000,  31200,  51000,  49920,  64738,  43000,  45000,
        39000, 125000,  55500,  30000,  35000, 130000,  53000,  44016,
        55000, 124000,  50000,  75000,  80000,  60000,  63540,  45000,
        82000,  58000,  90000,  35000, 110000,  75000,  92700,  29120,
       120000,  20800,  45000,  42000,  50000,  50000,  85000,  52000,
        79000,  70366,  42000,  42000,  74000,  90000,  27000,  52000,
        65000,  28250, 110500,  35000, 120000,  68675,  90000,  40000,
        98000,  53700, 196942,  60000,  35500,  38000,  65000, 100000,
        58000,  75000,  24000,  60000,  33900,  55000, 102000,  98450,
        32625,  70000,  34000,  50000,  50000,  28800,  23998,  65000,
        45000,  54184,  45000,  62500,  87000, 110000,  36500,  35000,
       120000, 113427,  52000,  18900,  82000,  74500,  51000,  65000,
        52000,  29000,  21600, 120000,  63000,  72000,  38862, 165000,
        85000,  58000, 101000,  60000,  97000, 140000,  59535,  60000,
        43805,  79000,  50000, 102000,  82000, 106000,  34000,  45000,
        95000,  71102,  86000,  80000,  73000,  29120,  35000,  83000,
        70000, 150000,  35000,  62189,  40000,  32400,  48906,  78000,
       130000,  40000,  60000,  82000,  70000,  45000,  72000,  40000,
        20000,  38000, 112000,  97500, 124000,  65000,  95000,  39000,
        33000,  51000,  50000,  60000,  59000,  36000,  51000,  79500,
        30000,  85000,  45000,  68000,  83000,  21600,  34500,  42000,
        32000, 120000,  50000,  48000,  30000,  92000,  40000,  80000,
        75000,  50000,  54000,  44000,  64000,  54000,  80000,  55000,
        32500,  49960,  60000,  73000, 120000,  33000,  78000,  40000,
        28116,  72000,  47000,  40000,  40000,  36000,  74000,  30540,
        50000,  47000,  85000,  43000,  89000,  51840, 125000, 179376,
        54000,  42000,  40000,  40000,  71000,  46000,  60000,  43000,
        66705,  75000,  40000,  50000,  52000,  18500,  90000,  55000,
        40000,  72000,  40000,  58250,  41000,  72800,  85000,  49500,
        94344,  82000, 108000,  75000,  67000,  65000,  80000,  69200,
        34000,  93500,  51000, 104000,  50000, 109000,  75000,  80000,
        40000,  22000,  30000,  66000,  48000,  49000, 110000, 150000,
        32400,  49200,  60900,  96895, 100000,  42500, 130000,  60000,
        51000, 160000,  60000, 113000,  23544, 160000,  36000,  75000,
        23000,  83000,  34553,  58000,  72300,  62000,  55000,  56000,
        67490,  65000, 100500,  35000,  33000,  55000,  30000,  72000,
        75000,  90000,  95000,  45000,  37000, 120000,  55000,  75000,
        58000,  45000,  65000,  72000,  80000,  68000,  50000,  52000,
        18000,  42000,  45000,  62000,  48000,  60000,  35000,  65000,
        61200, 104000,  40000,  43000,  40000,  63000,  38000,  68000,
        80000,  90000,  60000,  31400,  87000,  40000,  57600,  87000,
        50000,  31000, 101000,  38000,  98000,  34000,  48000,  70319,
        52380,  42000, 120000,  52000,  35000,  55000,  52000, 175000,
        70000, 105000,  70000,  93000,  49000, 137000,  40000,  52000,
        35000,  48470,  66000,  65000, 120000,  50000,  45000,  80000,
        59436,  56000,  57000,  40000,  40000,  96664,  60000, 160000,
        57000,  60000,  25000,  69500,  78500,  57000,  50000,  45000,
        46000,  84012,  85000,  94000,  40000, 150000, 190500,  65000,
        37702, 122600,  91560,  32000,  45000,  84000,  55000,  90000],
      dtype=int64)

In [27]:
np.random.choice(df['x'],replace=True, size=10)

array([ 82000,  66600,  20000,  32000,  65500, 125000,  46875,  65000,
        85000,  50000], dtype=int64)

In [52]:
list1=[]
for i in range(1,11):
    list1.append(list(np.random.choice(df['x'],replace=True, size=10)))
list1

[[55000, 50000, 56000, 130000, 100000, 115000, 72000, 30159, 48554, 44000],
 [40000, 107000, 70000, 57465, 48000, 70000, 72000, 60000, 40000, 60000],
 [41000, 40000, 65000, 58000, 108000, 63000, 50000, 63000, 35000, 37000],
 [83604, 44000, 60000, 30000, 117700, 49628, 15024, 63000, 65000, 81000],
 [60000, 73500, 96000, 55000, 70575, 60000, 105000, 70000, 72000, 46000],
 [54000, 26000, 95000, 140000, 96000, 60000, 120000, 109000, 55000, 78500],
 [61000, 38700, 110676, 135000, 35000, 85000, 33000, 32000, 54000, 115000],
 [25000, 118000, 34000, 47000, 70000, 77000, 75000, 85000, 28536, 54000],
 [102714, 45000, 50000, 55000, 21000, 50000, 80000, 38000, 195000, 32000],
 [88000, 42000, 50000, 118044, 98000, 60000, 83199, 100000, 51000, 65000]]

In [53]:
list2=[]
for i in range(1,101):
    list2.append(list(np.random.choice(df['x'],replace=True, size=10)))
list2

[[50000, 16000, 110000, 55000, 42000, 120000, 50000, 45000, 46000, 45000],
 [45684, 90840, 22500, 72000, 70000, 70000, 69500, 106000, 36000, 29000],
 [58000, 65000, 150000, 75000, 80000, 76000, 50000, 37000, 80000, 56000],
 [98600, 18200, 72000, 120000, 65000, 25000, 40000, 94500, 50000, 140000],
 [75000, 60000, 101000, 85000, 47000, 63000, 50000, 36000, 120000, 32000],
 [60000, 83000, 84000, 70000, 45700, 150000, 85000, 97000, 101837, 103000],
 [168000, 50000, 55000, 36000, 65000, 73000, 103000, 95000, 100000, 60000],
 [49000, 63000, 56000, 54000, 55000, 84000, 150000, 100000, 53000, 110000],
 [65440, 75000, 105000, 65000, 78425, 40000, 90000, 87500, 145000, 42000],
 [45000, 106000, 40000, 42000, 46000, 54000, 85000, 30000, 26000, 63800],
 [54115, 46000, 120000, 35000, 74000, 32000, 37400, 193000, 100000, 30000],
 [46000, 175000, 50000, 60000, 105000, 60000, 50000, 150000, 29200, 65000],
 [34000, 60000, 38000, 94176, 175000, 66622, 33000, 34000, 60000, 90000],
 [50000, 60000, 87500, 25000, 40000, 50000, 41100, 58000, 117000, 138000],
 [46000, 36300, 45000, 80000, 40000, 35000, 50000, 70000, 57000, 51000],
 [35000, 72000, 56804, 33000, 80000, 104000, 38000, 171600, 60000, 80000],
 [100000, 75000, 70004, 70000, 50000, 93500, 68000, 72000, 42000, 120000],
 [128000, 35055, 80000, 50000, 50000, 50000, 46000, 81000, 80000, 39000],
 [75000, 71000, 90000, 81000, 42000, 56000, 50000, 92000, 43000, 100000],
 [140000, 40000, 80000, 37000, 28000, 65000, 22875, 93000, 85000, 28000],
 [24000, 102000, 85000, 45000, 38208, 80000, 30000, 45000, 78996, 90000],
 [48000, 42500, 40000, 80000, 95000, 73500, 68399, 106000, 36000, 73158],
 [58000, 100000, 52000, 65000, 53000, 40000, 39520, 122000, 62000, 40000],
 [34000, 27000, 110000, 65000, 80000, 35000, 58000, 90000, 38000, 73000],
 [65000, 60000, 98000, 85000, 90000, 48000, 95000, 55000, 85000, 61000],
 [85000, 21000, 81000, 40000, 39600, 91800, 65000, 65000, 36000, 60000],
 [50000, 80000, 49920, 87000, 58500, 150000, 52000, 27000, 101000, 72000],
 [90000, 29000, 88000, 46000, 51000, 44000, 85000, 40000, 65000, 94000],
 [47800, 36000, 135000, 42000, 47000, 140000, 54000, 42340, 42000, 110000],
 [35000, 75000, 36000, 95000, 130000, 61000, 157000, 70000, 45000, 80000],
 [125000, 9600, 28500, 57688, 70000, 51000, 66000, 35000, 120000, 73000],
 [90000, 56000, 14798, 100000, 100000, 40000, 50000, 69000, 51000, 75000],
 [50000, 39000, 60000, 125000, 150000, 57000, 60000, 65000, 150000, 75000],
 [27000, 57650, 35000, 120000, 32000, 122000, 175000, 76763, 19296, 42000],
 [74000, 103000, 50000, 50734, 45000, 120000, 40000, 40000, 72000, 60000],
 [45000, 37000, 73500, 95000, 55000, 46079, 100000, 50000, 45000, 10350],
 [21768, 31200, 120000, 56035, 80000, 93000, 78000, 75000, 76000, 36000],
 [45000, 171600, 185000, 92000, 110000, 36729, 40000, 170000, 40000, 50000],
 [45000, 40164, 36600, 125000, 29120, 154000, 52000, 47500, 26400, 32000],
 [63000, 78000, 49000, 30000, 60000, 120000, 28000, 28000, 35000, 118000],
 [145000, 69000, 87000, 67846, 38400, 99996, 50000, 60000, 35000, 25000],
 [36000, 84000, 39000, 36000, 160000, 74000, 64000, 60000, 135000, 35000],
 [22000, 49000, 59000, 65000, 66000, 87300, 49000, 57000, 71000, 46236],
 [52000, 95000, 50000, 42000, 90000, 43500, 55000, 58000, 130000, 100000],
 [54000, 57000, 50000, 97000, 60000, 84000, 100000, 125000, 100000, 43000],
 [175000, 36000, 60000, 35000, 78000, 70000, 71000, 105000, 119800, 52423],
 [70000, 65000, 67177, 45000, 85000, 65000, 78000, 43000, 45000, 60000],
 [100000, 45000, 64000, 59000, 47000, 83000, 60000, 55000, 31000, 120000],
 [70575, 40000, 61000, 90000, 55000, 70000, 61000, 94957, 115000, 24985],
 [30000, 110000, 40000, 30000, 65000, 72000, 42000, 125000, 46728, 38000],
 [80000, 21000, 84000, 64000, 35000, 29559, 50000, 110000, 150000, 55000],
 [68000, 85000, 75000, 18000, 38000, 150000, 61440, 65000, 60000, 15080],
 [48470, 40000, 45000, 61250, 81000, 58000, 73000, 52000, 70000, 36120],
 [24000, 62000, 40000, 96000, 106000, 130405, 80000, 78000, 125000, 50000],
 [46000, 32000, 33400, 67190, 99000, 85000, 100000, 75000, 120000, 66000],
 [80000, 100000, 51000, 112000, 50000, 45000, 47000, 46680, 24000, 37392],
 [46000, 25000, 125000, 63000, 130000, 54000, 47710, 100000, 32000, 60000],
 [52000, 40000, 50000, 64000, 36000, 85000, 44000, 57000, 50000, 70000],
 [150000, 52800, 76000, 57200, 72000, 48000, 55000, 60000, 60000, 40016],
 [41000, 55000, 118000, 33000, 138000, 85000, 50000, 65000, 38474, 75000],
 [35400, 68000, 62000, 73000, 42000, 87370, 120000, 80000, 68500, 90000],
 [32000, 63205, 50000, 92700, 72000, 79780, 100000, 45000, 70000, 137500],
 [52000, 169000, 50000, 95000, 110000, 77650, 65000, 60000, 70000, 36000],
 [55500, 68000, 90000, 28720, 35000, 40000, 50000, 51204, 88000, 57000],
 [36500, 60000, 75000, 49000, 108000, 105000, 41000, 68000, 55400, 50000],
 [78000, 65000, 44000, 60000, 28000, 130000, 71000, 45000, 55000, 140000],
 [46000, 140000, 65000, 86708, 73000, 43000, 73000, 75000, 160000, 65000],
 [85000, 100000, 45000, 45000, 33000, 75000, 80000, 59000, 65000, 80000],
 [130000, 90000, 50859, 27040, 50000, 110000, 66300, 28000, 145000, 38000],
 [61000, 55824, 40000, 60000, 20000, 55000, 80000, 75000, 88000, 42000],
 [106000, 120000, 32000, 55000, 60000, 85000, 28000, 53500, 44000, 55000],
 [55000, 9000, 76763, 95000, 90000, 96000, 62397, 130000, 100000, 29900],
 [55000, 120000, 156000, 68000, 44532, 48000, 70000, 95000, 70000, 120000],
 [110000, 40000, 60000, 65000, 43310, 45000, 50000, 26880, 83000, 72000],
 [125000, 42000, 85000, 72850, 83500, 44320, 110000, 86000, 102000, 45000],
 [95000, 160000, 30000, 53000, 98000, 150000, 40000, 60300, 100000, 63000],
 [44000, 42000, 42000, 90000, 25000, 120000, 90000, 101000, 40560, 55000],
 [50000, 45000, 102000, 75000, 52000, 15500, 45000, 108000, 165000, 65000],
 [90450, 66000, 54000, 127500, 70000, 80000, 82500, 57000, 54000, 60000],
 [60000, 60000, 120000, 106000, 120000, 70000, 41000, 29000, 41000, 94000],
 [64800, 51376, 90000, 80000, 150000, 65000, 60507, 38000, 57996, 38000],
 [36000, 31320, 57000, 27600, 131600, 70000, 65000, 48000, 48000, 60000],
 [50000, 79000, 51000, 100000, 46800, 95004, 66000, 54000, 95919, 53700],
 [85000, 38000, 63650, 34014, 30000, 65000, 183000, 23000, 34272, 180000],
 [78000, 75000, 155000, 77000, 150000, 92000, 55000, 73000, 70000, 72000],
 [67980, 120000, 72000, 85000, 60000, 138500, 115000, 21000, 40000, 80000],
 [150000, 70000, 52000, 20000, 43971, 63500, 31303, 80000, 65000, 102050],
 [26240, 75000, 140000, 60000, 140000, 51000, 68000, 45000, 60000, 44016],
 [43200, 68000, 49500, 95000, 120000, 70000, 62200, 58000, 58000, 140000],
 [39930, 89000, 52000, 29000, 85000, 70000, 117000, 70000, 39000, 32000],
 [52000, 80000, 100000, 110000, 50000, 40000, 57500, 75000, 98000, 102000],
 [44000, 75000, 44000, 26000, 67000, 37000, 150000, 90000, 70000, 45000],
 [110000, 89200, 130000, 61000, 65000, 80000, 70050, 18000, 61402, 71944],
 [110000, 103000, 50000, 80000, 115000, 60000, 84996, 100000, 65000, 80000],
 [125000, 126500, 54800, 95000, 55000, 31000, 153000, 51000, 50000, 79000],
 [75000, 68000, 95000, 55000, 95000, 100000, 90800, 46000, 53000, 55000],
 [30000, 25000, 39500, 170000, 26748, 163000, 102820, 42342, 96000, 90000],
 [50000, 62370, 25000, 130000, 22000, 155000, 132562, 75000, 85000, 97000],
 [106000, 77000, 67000, 110000, 78000, 33500, 65000, 124000, 56000, 149000],
 [75000, 42000, 45000, 52000, 40000, 100290, 55000, 15000, 55990, 120000]]

In [50]:
list3=[]
for i in range(1,1001):
    list3.append(list(np.random.choice(df['x'],replace=True, size=10)))
list3

[]

In [51]:
list4=[]
for i in range(1,11):
    list4.append(list(np.random.choice(df['x'],replace=True, size=100)))
list4

[]

In [54]:
list5=[]
for i in range(1,11):
    list5.append(list(np.random.choice(df['x'],replace=True, size=100)))
list5

[[85000,
  69000,
  90000,
  60000,
  45000,
  48000,
  50000,
  100000,
  85000,
  50000,
  92000,
  78300,
  80000,
  22668,
  100156,
  33280,
  125000,
  44000,
  100000,
  55000,
  40000,
  60500,
  53000,
  55000,
  72000,
  60000,
  35000,
  72000,
  75000,
  36000,
  85000,
  54000,
  48000,
  130000,
  65700,
  55000,
  60000,
  80000,
  75000,
  37000,
  160000,
  160000,
  95000,
  85000,
  100000,
  39893,
  120000,
  90000,
  76000,
  33975,
  48000,
  72090,
  45000,
  40000,
  47694,
  60000,
  65000,
  100000,
  38862,
  85000,
  77000,
  77744,
  87106,
  62000,
  99976,
  60000,
  30000,
  105000,
  72000,
  117500,
  50000,
  60000,
  65000,
  75000,
  95000,
  43000,
  88000,
  105000,
  52000,
  35000,
  45000,
  9600,
  37000,
  66560,
  75000,
  30000,
  35000,
  82500,
  38000,
  145000,
  37000,
  30000,
  100000,
  33000,
  83000,
  136000,
  36000,
  75000,
  59000,
  68000],
 [45000,
  29000,
  109000,
  145000,
  83200,
  92000,
  49000,
  100000,
  55920,
  30000,
  187000,
  103793,
  38000,
  39996,
  22000,
  50000,
  80000,
  125000,
  60000,
  95000,
  44000,
  36500,
  52000,
  55200,
  62695,
  75000,
  42000,
  45000,
  41000,
  46000,
  46128,
  75000,
  48000,
  56000,
  60000,
  48057,
  24000,
  23000,
  96000,
  57000,
  112000,
  42000,
  50000,
  45000,
  60000,
  34000,
  83000,
  100000,
  45000,
  80000,
  42078,
  60000,
  50000,
  82500,
  85000,
  46000,
  52000,
  63223,
  36000,
  84000,
  23000,
  91000,
  58000,
  90000,
  75000,
  193000,
  60814,
  55000,
  65000,
  15000,
  73000,
  55000,
  43000,
  45000,
  37606,
  26000,
  70000,
  50000,
  58000,
  37000,
  92500,
  35000,
  90000,
  32000,
  74292,
  42000,
  110000,
  50000,
  30000,
  58000,
  70000,
  73000,
  93000,
  22000,
  98000,
  86000,
  67000,
  55000,
  60000,
  70000],
 [53000,
  120000,
  45000,
  45000,
  70000,
  75000,
  45000,
  100100,
  65000,
  65000,
  45000,
  110000,
  100000,
  20000,
  18000,
  58000,
  50000,
  35000,
  49000,
  47300,
  120000,
  25000,
  120000,
  13000,
  55000,
  87000,
  40000,
  100000,
  40000,
  52000,
  56000,
  58000,
  70000,
  135996,
  45000,
  35000,
  44000,
  60000,
  32000,
  78996,
  40000,
  60000,
  132000,
  50000,
  32800,
  23000,
  55000,
  45000,
  35000,
  100000,
  80000,
  28000,
  36000,
  75000,
  43300,
  137000,
  29060,
  65000,
  69000,
  108000,
  30000,
  68000,
  27000,
  53640,
  24000,
  75379,
  36000,
  103500,
  120000,
  42000,
  48000,
  91000,
  24000,
  130000,
  75000,
  53000,
  72000,
  85000,
  70000,
  68750,
  82000,
  115000,
  45334,
  70000,
  37000,
  31588,
  84700,
  35000,
  62000,
  38000,
  72000,
  115000,
  95000,
  44484,
  26000,
  60000,
  65000,
  91300,
  106000,
  39970],
 [64000,
  130000,
  48838,
  47200,
  70000,
  77000,
  28000,
  38050,
  78000,
  42000,
  55000,
  30072,
  50000,
  80000,
  115000,
  55000,
  64000,
  80000,
  85000,
  43000,
  74000,
  80000,
  154000,
  49000,
  50000,
  60204,
  87000,
  23000,
  16199,
  81000,
  114000,
  40000,
  34000,
  135000,
  51000,
  78000,
  100000,
  60000,
  70000,
  110000,
  105000,
  65000,
  52000,
  31200,
  33000,
  23579,
  45000,
  116000,
  72000,
  109804,
  27040,
  71000,
  88000,
  51784,
  95000,
  110000,
  60000,
  167000,
  64500,
  36000,
  97010,
  55200,
  90000,
  45000,
  105000,
  70000,
  48000,
  24000,
  18200,
  36000,
  40000,
  84000,
  44000,
  60000,
  165000,
  146500,
  112000,
  60000,
  32000,
  66408,
  38000,
  100000,
  57700,
  40000,
  21636,
  83000,
  110000,
  87500,
  50458,
  50000,
  60000,
  65000,
  90000,
  50000,
  55000,
  155000,
  68000,
  52000,
  35000,
  52000],
 [110000,
  41000,
  26416,
  33000,
  90000,
  50000,
  36000,
  45760,
  115000,
  65000,
  68000,
  47000,
  76000,
  145000,
  75000,
  47000,
  81000,
  80000,
  80000,
  195000,
  74600,
  190000,
  60000,
  29000,
  71000,
  153800,
  75000,
  110000,
  69000,
  44000,
  36000,
  40000,
  70000,
  24832,
  112000,
  10000,
  78000,
  50000,
  64000,
  35000,
  60000,
  70000,
  50000,
  82000,
  54000,
  115000,
  85000,
  85000,
  42452,
  75000,
  72000,
  80000,
  38000,
  25000,
  30000,
  34000,
  93340,
  80000,
  115000,
  44100,
  80000,
  65000,
  50000,
  90000,
  40000,
  27120,
  38000,
  45000,
  75000,
  33000,
  55000,
  100000,
  125000,
  42000,
  118000,
  95000,
  86000,
  60000,
  85000,
  90000,
  53000,
  56535,
  72168,
  90000,
  32000,
  50000,
  77496,
  40000,
  43160,
  15000,
  76920,
  95000,
  105000,
  85000,
  40000,
  56000,
  40500,
  112000,
  48000,
  125000],
 [40000,
  85000,
  60000,
  65000,
  70000,
  55000,
  69000,
  30000,
  7000,
  16400,
  50000,
  35000,
  75000,
  90000,
  100000,
  107100,
  110000,
  75000,
  48000,
  78500,
  45000,
  115000,
  45000,
  60000,
  75000,
  132000,
  72000,
  25000,
  33280,
  68000,
  32500,
  91000,
  28000,
  55000,
  46000,
  116335,
  52000,
  68000,
  34840,
  50000,
  58000,
  45000,
  31557,
  79000,
  60000,
  28000,
  39000,
  86000,
  39996,
  55000,
  53000,
  32000,
  135000,
  50000,
  105000,
  121000,
  83000,
  125000,
  125000,
  38000,
  72000,
  63000,
  62568,
  47800,
  25000,
  55000,
  139000,
  72000,
  98000,
  60000,
  39000,
  70000,
  82000,
  105000,
  27000,
  30000,
  85000,
  73000,
  150000,
  44000,
  119000,
  42000,
  165000,
  100265,
  17000,
  120000,
  60000,
  45000,
  82000,
  77425,
  38000,
  38400,
  55000,
  90000,
  116000,
  65000,
  110000,
  43000,
  30000,
  130000],
 [79000,
  62000,
  50000,
  50000,
  79000,
  55000,
  69000,
  150000,
  130000,
  58000,
  95000,
  33000,
  47000,
  68084,
  58446,
  15000,
  120000,
  34000,
  102000,
  110000,
  60000,
  65000,
  30000,
  75000,
  60782,
  34000,
  64000,
  27600,
  115000,
  91000,
  63000,
  48000,
  49000,
  78000,
  75000,
  42000,
  102000,
  50236,
  58000,
  30000,
  46000,
  60000,
  135000,
  93000,
  49000,
  68000,
  60000,
  64000,
  61000,
  140000,
  70000,
  69996,
  40000,
  48173,
  52000,
  74628,
  85000,
  78000,
  141000,
  33000,
  60000,
  40000,
  47245,
  92000,
  40000,
  48000,
  98984,
  105000,
  65500,
  38000,
  72000,
  45000,
  55560,
  25563,
  68000,
  95000,
  36000,
  28000,
  48000,
  49000,
  90000,
  84000,
  46000,
  84908,
  30000,
  140000,
  80200,
  50000,
  75000,
  73000,
  70800,
  80000,
  165000,
  123000,
  27200,
  180000,
  27600,
  43000,
  53000,
  65000],
 [35000,
  140000,
  55000,
  29000,
  57690,
  156980,
  60000,
  175000,
  21000,
  70000,
  47520,
  107000,
  32090,
  59000,
  73000,
  98500,
  110000,
  66000,
  92000,
  105000,
  53000,
  165000,
  75000,
  51000,
  150000,
  61426,
  85000,
  78000,
  65000,
  75000,
  65760,
  64176,
  75000,
  60825,
  35000,
  102000,
  75000,
  55076,
  81000,
  65000,
  120000,
  50000,
  65000,
  95000,
  31000,
  61000,
  21000,
  35000,
  45000,
  85000,
  120000,
  60000,
  62000,
  80000,
  65000,
  70000,
  73000,
  96000,
  40000,
  95000,
  45000,
  45000,
  150000,
  125400,
  18000,
  37000,
  175000,
  43000,
  13000,
  45000,
  115000,
  45722,
  34000,
  40000,
  41000,
  70000,
  45000,
  14000,
  43871,
  87000,
  132000,
  55000,
  36000,
  135000,
  109000,
  50000,
  54000,
  27000,
  75000,
  50707,
  85000,
  40000,
  34000,
  70000,
  28700,
  72000,
  74400,
  67000,
  87000,
  80000],
 [52000,
  85000,
  123000,
  52000,
  40800,
  96000,
  60000,
  82000,
  70000,
  105000,
  50000,
  71000,
  34000,
  92000,
  22000,
  57000,
  48852,
  75000,
  80100,
  74000,
  60000,
  29000,
  55000,
  53000,
  76070,
  24800,
  67920,
  36500,
  170000,
  40000,
  90000,
  45000,
  42000,
  56000,
  50000,
  70000,
  120000,
  47000,
  73000,
  62000,
  77000,
  71000,
  42000,
  45000,
  90000,
  33000,
  44000,
  82000,
  135000,
  71000,
  165000,
  57438,
  90000,
  46000,
  73000,
  42000,
  50000,
  50000,
  97000,
  74000,
  60000,
  80000,
  140000,
  35000,
  60000,
  80000,
  124800,
  33000,
  79000,
  28000,
  48000,
  90000,
  42000,
  45000,
  72000,
  57500,
  60000,
  110000,
  55000,
  40000,
  72500,
  75000,
  83200,
  89000,
  30000,
  50000,
  130000,
  42500,
  41400,
  59800,
  155000,
  40000,
  80000,
  60000,
  77000,
  110000,
  42000,
  30000,
  46000,
  40000],
 [95000,
  50000,
  41990,
  60000,
  102000,
  48000,
  124000,
  65000,
  64800,
  72000,
  60000,
  35000,
  43900,
  95000,
  72000,
  45000,
  76800,
  85000,
  110000,
  49000,
  67500,
  132000,
  85000,
  66000,
  55000,
  32000,
  50000,
  98916,
  104000,
  75000,
  32200,
  136000,
  59500,
  65000,
  25000,
  45000,
  87700,
  58310,
  138000,
  110000,
  55000,
  62000,
  67850,
  65000,
  65000,
  57000,
  140000,
  33000,
  110000,
  50000,
  70000,
  60500,
  99996,
  68000,
  45000,
  70000,
  47000,
  58000,
  45000,
  104000,
  50000,
  112080,
  35000,
  60000,
  90000,
  55000,
  120000,
  22500,
  71500,
  41990,
  110000,
  66480,
  110000,
  13000,
  167000,
  74800,
  72550,
  45000,
  35000,
  25000,
  38000,
  104000,
  29000,
  75000,
  45000,
  90000,
  40000,
  51960,
  51000,
  65249,
  60000,
  35283,
  80000,
  25000,
  180000,
  72000,
  50000,
  100000,
  43000,
  58000]]